import { developersApi } from '../apis/developers_api'

import { authenticationService } from './authentication_service';

export class DevelopersService {
    /**
     * Creates a new developer profile
     * 
     * Returns the developer profile on success, throws error message on error
     */
    async createProfile(developer) {
        return await developersApi.createProfile(developer, await authenticationService.getCurrentUser());
    }

    /**
     * Returns the profile of the developer with the given id
     */
    async getProfile(id) {
        return fakeDevelopers.find((obj) => obj._id === id);

        // TODO(FIX)
        // return await developersApi.getProfile(id, await authenticationService.getCurrentUser());
    }

    /**
     * Updates the profile of the developer with the given id.
     * 
     * Returns the new developer profile on success, throws error message on error
     */
    async updateProfile(id, newProfileData) {
        return await developersApi.updateProfile(id, newProfileData, await authenticationService.getCurrentUser());
    }

    /**
     * Returns a list of all developer profiles
     */
    async listDevelopers() {
        var promise = new Promise((resolve, reject) => {
            setTimeout(() => resolve(fakeDevelopers), 4000);
        })

        return promise;
        // TODO(FIX)
        // return await developersApi.listDevelopers(await authenticationService.getCurrentUser());
    }

    /**
     * Returns the public profile of the developer with the given name and id.
     * 
     * TODO(Remove this and make getProfile a public route that fails if the the developers service is not public)
     */
    async getPublicProfile(name, id) {
        return await developersApi.getPublicProfile(name, id);
    }


    static __developersService = null;
    static getInstance() {
        if (DevelopersService.__developersService === null)
            return DevelopersService.__developersService = new DevelopersService();
    }
}


const developersService = DevelopersService.getInstance();
export { developersService };

const fakeDevelopers = [
    {
        "_id": 'myDeveloperId', // This field is auto-generated by Mongo
        "firstName": "Patrick Rashidi",
        "lastName": "",
        "shortBiography": "Full Stack Developer and Test Automation Engineer",
        "isPublic": true,
        "profilePicture": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',

        "socialMedia": [
            {
                "name": "youtube",
                "link": "http://bit.ly/patrick-rashidi"
            },
            {
                "name": "github",
                "link": "https://github.com/prashidi"
            }
        ],

        "education": [
            {
                "schoolName": "Cape Peninsula University of Technology",
                "schoolLocation": "Cape Town",
                "schoolLogo": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',
                "fieldsOfStudy": "Computer Systems Engineering",
                "achievements": "Graduated with a diploma"
            }
        ],
        "experience": [
            {
                "companyName": "Aerobotics",
                "companyLogo": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',
                "title": "Data Operations and QC Intern",
                "duration": "December 2018 - Present",
                "jobDescription": "Build and align aerial imagery taken with drones andtroubleshoot where automated processing failed. Also Trackimage processing jobs using the web based platform and SQL.End-to-End Tests: Created highly performant and extremely stable end-to-end test suite using Cypres"
            }, {
                "companyName": "Aerobotics",
                "companyLogo": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',
                "title": "Data Operations and QC Intern",
                "duration": "December 2018 - Present",
                "jobDescription": "Build and align aerial imagery taken with drones andtroubleshoot where automated processing failed. Also Trackimage processing jobs using the web based platform and SQL.End-to-End Tests: Created highly performant and extremely stable end-to-end test suite using Cypres"
            },
            {
                "companyName": "Aerobotics",
                "companyLogo": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',
                "title": "Data Operations and QC Intern",
                "duration": "December 2018 - Present",
                "jobDescription": "Build and align aerial imagery taken with drones andtroubleshoot where automated processing failed. Also Trackimage processing jobs using the web based platform and SQL.End-to-End Tests: Created highly performant and extremely stable end-to-end test suite using Cypres"
            },
        ],
        "technicalSkills": [
            "react",
            "nodeJs",
            "android",
            "php",
            "java",
            "javaScript",
            "python",
            "django"
        ],
        "hobbies": [
            "music",
            "exercise",
            "video games"
        ],
        "hardSkills": [
            {
                "id": "java",
                "rating": 5,
                "years": 6
            },
            {
                "id": "javaScript",
                "rating": 5,
                "years": 4
            },
            {
                "id": "react",
                "rating": 5,
                "years": 2
            },

            // The frontend will know which group each hardskill belogs to based on id. E.g java belongs to 'Languages', while react belong to 'Frontend'
        ],
        "softSkills": [
            {
                "id": "selfMotivation",
                "rating": 5,
                "description": "Taking initiative \nkeen to learn \nGoogle Food"
            },
            {
                "id": "timeManagement",
                "rating": 3,
                "description": "Tasks are well executed in time, and always attended meetings in time. Great management given multiple commitments such as school & zaio projects",
            }
        ]
    },

    {
        "_id": 'myDeveloperId', // This field is auto-generated by Mongo
        "firstName": "Batandwa Mgutsi",
        "lastName": "",
        "shortBiography": "Junior Software developer at FilledStacks",
        "isPublic": true,
        "profilePicture": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',

        "socialMedia": [
            {
                "name": "youtube",
                "link": "http://bit.ly/patrick-rashidi"
            },
            {
                "name": "github",
                "link": "https://github.com/prashidi"
            }
        ],

        "education": [
            {
                "schoolName": "Cape Peninsula University of Technology",
                "schoolLocation": "Cape Town",
                "schoolLogo": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',
                "fieldsOfStudy": "Computer Systems Engineering",
                "achievements": "Graduated with a diploma"
            }
        ],
        "experience": [
            {
                "companyName": "Aerobotics",
                "companyLogo": 'https://lafeber.com/pet-birds/wp-content/uploads/2020/03/macaw-face-px-ara-3695678-300x300.jpg',
                "title": "Data Operations and QC Intern",
                "duration": "March 2020 - Present",
                "jobDescription": "Build and align aerial imagery taken with drones andtroubleshoot where automated processing failed. Also Trackimage processing jobs using the web based platform and SQL.End-to-End Tests: Created highly performant and extremely stable end-to-end test suite using Cypres"
            },
        ],
        "technicalSkills": [
            "react",
            "nodeJs",
            "android",
            "php",
            "java",
            "javaScript",
            "python",
            "django"
        ],
        "hobbies": [
            "music",
            "exercise",
            "video games"
        ],
        "hardSkills": [
            {
                "id": "java",
                "rating": 5,
                "years": 6
            },
            {
                "id": "javaScript",
                "rating": 5,
                "years": 4
            },
            {
                "id": "react",
                "rating": 5,
                "years": 2
            },

            // The frontend will know which group each hardskill belogs to based on id. E.g java belongs to 'Languages', while react belong to 'Frontend'
        ],
        "softSkills": [
            {
                "id": "selfMotivation",
                "rating": 5,
                "description": "Taking initiative \nkeen to learn \nGoogle Food"
            },
            {
                "id": "timeManagement",
                "rating": 3,
                "description": "Tasks are well executed in time, and always attended meetings in time. Great management given multiple commitments such as school & zaio projects",
            }
        ]
    }

];